import { t as tr, message, errorText } from '../shared/i18n.mjs';
import { catalog, net, classification, compliant, flags, execution, performance, groups, periodRange, dateKey, wallTime } from '../shared/core.mjs';
import { esc, glyph, command, options, field, pick, toggle, note, imageGallery } from './views.js';

const num = (name, label, value, extra = '') => field(name,label,value ?? '','number',`step="any" ${extra}`);
const grid = (content, className = '') => `<div class="form-grid ${className}">${content}</div>`;
const panel = (title, content, extra = '') => `<section class="panel ${extra}">${title ? `<div class="panel-heading"><h2>${tr(title.replaceAll('&middot;', '·'))}</h2></div>` : ''}${content}</section>`;
const disclosure = (title, content, id = '') => `<details class="editor-details" ${id ? `id="${id}"` : ''}><summary>${tr(title.replaceAll('&middot;', '·'))}</summary><div>${content}</div></details>`;
const checklist = (name, values, selected) => `<div class="checklist">${[...new Set([...values,...selected])].sort().map(value=>toggle(name,value,selected.includes(value),`value="${esc(value)}"`)).join('')}</div>`;
const rating = (name,label,value,min=0) => `<div class="rating"><label for="${name}">${tr(label)}</label><input id="${name}" name="${name}" type="range" min="${min}" max="10" step="1" value="${value}"><output>${value}</output></div>`;
const money = (n,data) => new Intl.NumberFormat('tr-TR',{style:'currency',currency:data.preferences.currency}).format(n);
const number = value => value == null ? '\u2014' : value.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
const r = value => value == null ? '\u2014' : `${value>0?'+':''}${value.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}R`;
const percent = value => value.toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
const tone = value => value>0?'positive':value<0?'negative':'muted';
const badge = (text,color='muted') => `<span class="badge ${color}">${esc(tr(text))}</span>`;
export const messages = {'VALID WINNER':'Good process, positive outcome','VALID LOSER':'Good process, normal loss','INVALID WINNER':'Profitable outcome, invalid execution','INVALID LOSER':'Review the process before the outcome','BREAKEVEN':'Flat outcome. Evaluate execution independently.'};
export function processPreview(t) { const type=classification(t);return `${badge(type,type.startsWith('INVALID')?'warning':type==='VALID LOSER'?'blue':tone(net(t)))}<p>${tr(messages[type])}</p>`; }
export function attachments(shots) {
  return `<div class="line">${pick('attachment-category','Category',catalog.screenshotCategories,'Entry')}${command('add-images','Add images...','image-plus')}</div><div class="drop-zone" tabindex="0" role="button" aria-label="Ekran görüntüsü ekle veya sürükle">${glyph('image-plus')}<span>Bilgisayarındaki ekran görüntülerini sürükle</span><small>PNG, JPEG, HEIC, TIFF · dosya başına en çok 30 MB</small></div><div id="draft-shots">${imageGallery(shots,true)}</div>`;
}
export function tradeEditor(t,data,shots,isNew) {
  const option=(name,label,values,selected)=>pick(name,label,[...new Set([...values,selected])].sort(),selected);
  const conditional=(name,content,visible)=>`<div data-conditional="${name}" ${visible?'':'hidden'}>${content}</div>`;
  const executionPanel=panel('01 / THE EXECUTION',
    grid(`<div>${field('instrument','Instrument',t.instrument,'text','list="symbols" required')}<datalist id="symbols">${data.instruments.filter(i=>i.enabled).map(i=>`<option value="${esc(i.symbol)}">`).join('')}</datalist><select id="choose-instrument" aria-label="Enstrüman seç">${options(data.instruments.filter(i=>i.enabled).map(i=>i.symbol),'','Choose instrument')}</select></div>`+option('direction','Direction',['Long','Short'],t.direction)+field('date','Entry time',wallTime(t.date,data.preferences.timezone),'datetime-local','required'))+
    grid(num('grossPnL',`Gross PnL ${data.preferences.currency}`,t.grossPnL,'required')+num('rMultiple','R multiple',t.rMultiple)+option('session','Session',data.preferences.sessions,t.session))+
    grid(pick('setupID','Setup',data.setups.map(s=>[s.id,s.name]),t.setupID,'Unassigned')+option('grade','Grade',['A+','A','B','C','D','F'],t.grade),'two')+
    (!data.setups.length?`<div class="line"><input id="quick-setup" placeholder="İlk stratejine bir ad ver" aria-label="İlk stratejine bir ad ver">${command('quick-setup','Create setup')}</div>`:'')+
    "<p class=\"caption\">Brüt K/Z masraflar öncesidir. R isteğe bağlıdır; elle girilebilir veya net K/Z ve riskten hesaplanabilir.</p>",'execution-general');
  const processPanel=panel('02 / PROCESS BEFORE OUTCOME',`<div class="switch">${toggle('followsPlan','Fully according to my trading plan',t.followsPlan)}</div><div id="broken-rule-fields" ${!t.followsPlan||t.brokenRules.length?'':'hidden'}>${checklist('brokenRules',[...catalog.rules,...data.rules.map(r=>r.name)],t.brokenRules)}<div class="line"><input id="custom-broken-rule" placeholder="İhlal edilen özel kural" aria-label="İhlal edilen özel kural">${command('add-broken-rule','Add')}</div></div><div id="process-preview" class="line">${processPreview(t)}</div>`,'editor-process');
  const prices=disclosure('Prices, risk & duration',grid(num('entryPrice','Entry price',t.entryPrice)+num('stopLoss','Stop loss',t.stopLoss)+num('takeProfit','Take profit',t.takeProfit)+num('exitPrice','Exit price',t.exitPrice),'four')+grid(num('positionSize','Position size',t.positionSize,'min="0"')+num('riskDollars',`Risk ${data.preferences.currency}`,t.riskDollars,'min="0"')+num('riskPercent','Risk %',t.riskPercent,'min="0"')+num('fees','Fees',t.fees,'min="0" required'),'four')+`<div class="line"><span id="price-preview"></span>${command('calculate-r','Calculate R from net PnL')}</div><div class="line">${toggle('record-exit','Record exit time',t.exitDate!=null)}<span id="exit-time-field" ${t.exitDate!=null?'':'hidden'}>${field('exitDate','Exit',wallTime(t.exitDate,data.preferences.timezone),'datetime-local')}</span></div>`,'prices-section');
  const market=disclosure('Market context & liquidity',grid(option('bias','HTF bias',['Bullish','Bearish','Neutral'],t.bias)+toggle('htfAligned','HTF alignment',t.htfAligned),'two')+"<small>Bağlam zaman dilimleri</small>"+checklist('contextTimeframes',catalog.timeframes,t.contextTimeframes)+grid(field('drawOnLiquidity','Draw on liquidity / custom',t.drawOnLiquidity)+`<label>Likidite referansı<select id="liquidity-reference">${options(catalog.liquidity,t.drawOnLiquidity,'Choose reference')}</select></label>`,'two')+"<small>Alınan likidite</small>"+checklist('liquidityTaken',catalog.sweeps,t.liquidityTaken)+toggle('sweepValid','Liquidity sweep valid',t.sweepValid));
  const qt=disclosure('Quarterly Theory &middot; QT',toggle('qt.enabled','QT enabled',t.qt.enabled)+conditional('qt.enabled',grid(option('qt.higherQuarter','Higher timeframe quarter',['Q1','Q2','Q3','Q4'],t.qt.higherQuarter)+option('qt.dailyQuarter','Daily quarter',['Q1','Q2','Q3','Q4'],t.qt.dailyQuarter),'two')+grid(option('qt.cycle90','90 minute cycle',['Q1','Q2','Q3','Q4'],t.qt.cycle90)+option('qt.cycle22','22.5 minute cycle',['Q1','Q2','Q3','Q4'],t.qt.cycle22),'two')+option('qt.phase','QT phase',['Accumulation','Manipulation','Distribution','Continuation'],t.qt.phase)+grid(toggle('qt.trueOpen','True open respected',t.qt.trueOpen)+toggle('qt.aligned','QT bias aligned',t.qt.aligned)+toggle('qt.valid','QT model valid',t.qt.valid)),t.qt.enabled));
  const mmxm=disclosure('Market Maker Model &middot; MMXM',option('mmxm.model','MMXM',['None','Market Maker Buy Model','Market Maker Sell Model'],t.mmxm.model)+conditional('mmxm.model',grid([['consolidation','Original consolidation'],['manipulation','Manipulation'],['displacement','Displacement'],['repricing','Repricing'],['reversal','Smart money reversal'],['target','Opposing liquidity target'],['valid','MMXM valid']].map(([key,label])=>toggle(`mmxm.${key}`,label,t.mmxm[key])).join('')),t.mmxm.model!=='None'));
  const po3=disclosure('Power of Three &middot; PO3',grid(option('po3.phase','PO3 phase',['Accumulation','Manipulation','Distribution'],t.po3.phase)+option('po3.manipulationDirection','Manipulation direction',['Up','Down'],t.po3.manipulationDirection)+toggle('po3.valid','PO3 valid',t.po3.valid)));
  const divergence=disclosure('SSMT & TSMO confirmations',grid(option('ssmt.confirmation','SSMT confirmation',['Yes','No','Not Required'],t.ssmt.confirmation)+toggle('ssmt.valid','Valid SSMT',t.ssmt.valid),'two')+option('ssmt.type','SSMT type',['High divergence','Low divergence','Intermarket divergence','Time-based divergence'],t.ssmt.type)+`<div id="market-checklist">${checklist('ssmt.markets',['NQ','ES','YM','DXY','Gold','EUR','GBP'],t.ssmt.markets)}</div><div class="line"><input id="custom-market" placeholder="Özel referans piyasa" aria-label="Özel referans piyasa">${command('add-market','Add market')}</div>`+grid(option('tsmo','TSMO confirmation',['Yes','No','Not Required'],t.tsmo)+toggle('tsmoValid','TSMO valid',t.tsmoValid),'two')+"<p class=\"caption\">Bir teyit, yalnızca mevcut ve geçerli olduğunda analize dahil edilir.</p>");
  const crt=disclosure('Candle Range Theory &middot; CRT',toggle('crt.enabled','CRT setup',t.crt.enabled)+conditional('crt.enabled',grid(option('crt.timeframe','CRT timeframe',catalog.timeframes,t.crt.timeframe)+num('crt.high','Range high',t.crt.high)+num('crt.low','Range low',t.crt.low))+grid(option('crt.liquidityTaken','Liquidity taken',['High','Low'],t.crt.liquidityTaken)+toggle('crt.reentry','CRT re-entry',t.crt.reentry)+toggle('crt.confirmed','CRT confirmed',t.crt.confirmed)),t.crt.enabled));
  const entry=disclosure('Entry model & confirmations',option('entryTimeframe','Entry timeframe',['15M','5M','3M','1M'],t.entryTimeframe)+checklist('confirmations',catalog.confirmations,t.confirmations));
  const scores=disclosure('Execution grading',[['marketRead','Market read'],['entry','Entry execution'],['compliance','Rule compliance'],['risk','Risk management'],['management','Trade management'],['psychology','Psychology'],['recognition','Pattern recognition']].map(([key,label])=>rating(`scores.${key}`,label,t.scores[key])).join('')+`<div class="line"><span>Genel puan</span><span id="overall-score" class="positive">${execution(t).toFixed(0)} / 100</span></div>`);
  const emotions=disclosure('Emotional journal',"<small>ÖNCESİ</small>"+['confidence','stress','fomo','focus'].map(key=>rating(`emotional.${key}`,key==='fomo'?'FOMO':key[0].toUpperCase()+key.slice(1),t.emotional[key],1)).join('')+"<small>SONRASI</small>"+rating('emotional.satisfaction','Execution satisfaction',t.emotional.satisfaction,1)+toggle('emotional.takeAgain','I would take this trade again',t.emotional.takeAgain)+checklist('emotional.emotions',catalog.emotions,t.emotional.emotions));
  const notes=disclosure('Trade thesis & review notes',[['thesis','Trade thesis'],['entry','Why did I enter?'],['confirmation','What confirmed the trade?'],['invalidation','What invalidated the setup?'],['correct','What did I do correctly?'],['incorrect','What did I do incorrectly?'],['differently','What would I do differently?'],['lesson','Key lesson']].map(([key,label])=>note(`notes.${key}`,label,t.notes[key])).join(''),'notes-section');
  return `<form id="edit-form" class="editor-form"><header><div><h2>${tr(isNew?'New execution':'Edit execution')}</h2><p class="subtitle">Temel bilgileri kaydet. Gerektiğinde ayrıntıları ekle.</p></div><div class="actions">${command('close-editor','Cancel')}<button type="submit" class="primary">İşlemi kaydet</button></div></header><div class="body">${executionPanel}${processPanel}${prices}${market}${qt}${mmxm}${po3}${divergence}${crt}${entry}${scores}${emotions}${notes}${panel('SCREENSHOTS',attachments(shots))}${field('tags','Tags, separated by commas',t.tags.join(', '))}</div><p id="form-error" class="error" role="alert"></p></form>`;
}
export function setupEditor(s,shots) {
  return `<form id="edit-form"><header><h2>Strateji defteri</h2><div class="actions">${command('close-editor','Cancel')}<button type="submit" class="primary">Stratejiyi kaydet</button></div></header><div class="body">${field('name','Setup name',s.name,'text','required')}${note('summary','One-line description',s.summary)}${[['conditions','Ideal conditions'],['entry','Entry rules'],['invalidation','Invalidation rules'],['target','Target rules'],['risk','Risk rules']].map(([key,label])=>note(key,label,s[key])).join('')}${panel('IDEAL EXAMPLES',attachments(shots))}</div><p id="form-error" class="error" role="alert"></p></form>`;
}
export function reviewSnapshot(data,period,date) {
  const range=periodRange(date,period,data.preferences.timezone),trades=data.trades.filter(t=>{const key=dateKey(t.date,data.preferences.timezone);return key>=range.from&&key<=range.to;}),p=performance(trades),setups=groups(trades,'Setup').sort((a,b)=>(b.averageR??-Infinity)-(a.averageR??-Infinity)),ordered=[...trades].sort((a,b)=>net(b)-net(a));
  const metric=(title,value)=>`<article class="metric"><h3>${tr(title.replaceAll('&middot;', '·'))}</h3><strong>${value}</strong></article>`;
  return `<p class="caption">${range.from} - ${range.to} &middot; Güncel istatistikler</p><div class="metrics three">${metric('Trades',p.count)}${metric('Net PnL',money(p.netPnL,data))}${metric('R',r(p.totalR))}</div>`+panel('REVIEW SNAPSHOT',[
    ['WR / PF / Expectancy',`${percent(p.winRate)} / ${p.profitFactor==null?p.grossProfit?'\u221e':'\u2014':number(p.profitFactor)} / ${r(p.averageR)}`],['Best setup',setups[0]?.name||'\u2014'],['Worst setup',setups.at(-1)?.name||'\u2014'],['Best trade',ordered[0]?`${ordered[0].instrument} / ${money(net(ordered[0]),data)}`:'\u2014'],['Worst trade',ordered.at(-1)?`${ordered.at(-1).instrument} / ${money(net(ordered.at(-1)),data)}`:'\u2014'],['Most common mistake',groups(trades,'Mistakes').sort((a,b)=>b.count-a.count)[0]?.name||'None recorded'],['Rule compliance / Execution',`${percent(p.compliance)} / ${p.executionScore.toFixed(0)}/100`]
  ].map(([label,value])=>`<div class="line"><span class="muted">${tr(label)}</span><span>${esc(value)}</span></div>`).join('')+"<p class=\"caption\">Stratejiler kaydedilen ortalama R'ye göre sıralanır. İşlemler değiştiğinde istatistikler güncellenir.</p>");
}
export function reviewEditor(item,data) {
  return `<form id="edit-form"><header><h2>Performans değerlendirmesi</h2><div class="actions">${command('close-editor','Cancel')}<button type="submit" class="primary">Değerlendirmeyi kaydet</button></div></header><div class="body"><div class="line">${pick('period','Period',['Daily','Weekly','Monthly'],item.period)}${field('date','Contains date',dateKey(item.date,data.preferences.timezone),'date','required')}</div><div id="review-snapshot" class="stack">${reviewSnapshot(data,item.period,item.date)}</div>${[['worked','What worked?'],['didNot',"What didn't?"],['repeatNext','What should I repeat?'],['stop','What should I stop doing?'],['adjustment','What is one adjustment for the next period?']].map(([key,label])=>note(key,label,item[key])).join('')}</div><p id="form-error" class="error" role="alert"></p></form>`;
}
export function detailView(t,data) {
  const f=flags(t),type=classification(t),shots=data.screenshots.filter(s=>s.tradeID===t.id).map(s=>s.screenshot),planned=t.entryPrice!=null&&t.stopLoss!=null&&t.takeProfit!=null&&t.entryPrice!==t.stopLoss?Math.abs(t.takeProfit-t.entryPrice)/Math.abs(t.entryPrice-t.stopLoss):null;
  const row=(label,value)=>`<div class="read-row"><span>${tr(label)}</span><span>${esc(value||tr('Not recorded'))}</span></div>`;
  const read=(label,value)=>`<div class="read-note"><small>${tr(label)}</small><p>${esc(value||tr('Not recorded'))}</p></div>`;
  const sequence=[['HTF',t.bias,t.htfAligned],['LIQUIDITY',t.liquidityTaken[0]||'Unspecified',t.sweepValid],['QT',t.qt.enabled?t.qt.dailyQuarter:'Not used',f.QT],['SSMT',t.ssmt.confirmation,f.SSMT],['CRT',t.crt.enabled?t.crt.timeframe:'Not used',f.CRT],['CISD',t.entryTimeframe,t.confirmations.includes('CISD')],['ENTRY',t.direction,compliant(t)],['TARGET',t.drawOnLiquidity||'Unspecified',!t.brokenRules.includes('Ignored target')]];
  return `<form class="detail-form"><header><span class="eyebrow">İŞLEM DEĞERLENDİRMESİ</span><div class="actions">${command('delete-record','Delete','','class="danger"')}${command('edit-trade','Edit trade')}${command('close-editor','Done')}</div></header><div class="body"><div class="review-title"><div><div class="line"><h1>${esc(t.instrument)}</h1>${badge(t.direction.toUpperCase(),'blue')}${badge(t.grade)}</div><h2 class="regular-title muted">${esc(t.setupName)}</h2><small>${new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short',timeZone:data.preferences.timezone}).format(t.date)} &middot; ${esc(tr(t.session))}</small></div><div><strong class="${tone(t.rMultiple||0)}">${r(t.rMultiple)}</strong><span class="${tone(net(t))}">${money(net(t),data)}</span></div></div>${panel('',`<div class="line">${processPreview(t)}</div>${!compliant(t)?`<p class="warning">${esc(t.brokenRules.map(tr).join(' / '))}</p>`:''}`)}${panel('EXECUTION SEQUENCE',`<div class="sequence-scroll"><div class="sequence">${sequence.map(([title,text,valid])=>`<div class="sequence-node"><div><i class="${valid?'positive':title==='ENTRY'?'negative':'warning'}">${valid?'&#10003;':'-'}</i></div><strong>${tr(title.replaceAll('&middot;', '·'))}</strong><small>${esc(tr(text))}</small></div>`).join('')}</div></div><p class="caption">Yeşil: teyitli · Sarı: eksik veya teyitsiz · Kırmızı: kural ihlali. Bunlar senin kaydettiğin gözlemlerdir.</p>`)}<div class="metrics">${[['Overall process',execution(t).toFixed(0)+'/100'],['Risk',t.riskDollars==null?'\u2014':money(t.riskDollars,data)],['Planned RR',number(planned)],['Duration',t.exitDate==null?'\u2014':Math.floor((t.exitDate-t.date)/60000)+' dk']].map(([title,value])=>`<article class="metric"><h3>${tr(title.replaceAll('&middot;', '·'))}</h3><strong>${value}</strong></article>`).join('')}</div>${panel('THESIS & LESSON',read('Trade thesis',t.notes.thesis)+read('Key lesson',t.notes.lesson))}${panel('VISUAL REVIEW',shots.length?imageGallery(shots):"<p class=\"caption\">Ekran görüntüsü yok. Görsel eklemek için işlemi düzenle.</p>")}${panel('CONTEXT & EXECUTION',[
    ['Prices',`Giriş ${number(t.entryPrice)} / Stop ${number(t.stopLoss)} / Kâr al ${number(t.takeProfit)} / Çıkış ${number(t.exitPrice)}`],['Size / fees',`${number(t.positionSize)} / ${money(t.fees,data)} masraf`],['Context timeframes',t.contextTimeframes.map(tr).join(', ')],['Liquidity taken',t.liquidityTaken.map(tr).join(', ')],['QT',`HTF ${t.qt.higherQuarter} / Günlük ${t.qt.dailyQuarter} / 90m ${t.qt.cycle90} / 22.5m ${t.qt.cycle22} / ${tr(t.qt.phase)}`],['MMXM',tr(t.mmxm.model)+(t.mmxm.valid?' / Geçerli':' / Teyitsiz')],['PO3',`${tr(t.po3.phase)} / Manipülasyon ${tr(t.po3.manipulationDirection)} / ${t.po3.valid?'Geçerli':'Teyitsiz'}`],['SSMT',`${tr(t.ssmt.type)} / ${t.ssmt.markets.join(', ')} / ${f.SSMT?'Geçerli':'Teyitsiz'}`],['TSMO',tr(t.tsmo)+(t.tsmoValid?' / Geçerli':' / Teyitsiz')],['CRT',`${t.crt.timeframe} / Aralık ${number(t.crt.low)} - ${number(t.crt.high)} / ${tr(t.crt.liquidityTaken)} alındı`],['Confirmations',t.confirmations.map(tr).join(', ')],['Tags',t.tags.join(', ')]
  ].map(([label,value])=>row(label,value)).join(''))}${panel('EXECUTION SCORES',row('Market / Entry / Rules',`${t.scores.marketRead} / ${t.scores.entry} / ${t.scores.compliance}`)+row('Risk / Management',`${t.scores.risk} / ${t.scores.management}`)+row('Psychology / Recognition',`${t.scores.psychology} / ${t.scores.recognition}`))}${panel('EMOTIONAL JOURNAL',row('Before',`Güven ${t.emotional.confidence} / Stres ${t.emotional.stress} / FOMO ${t.emotional.fomo} / Odak ${t.emotional.focus}`)+row('After',`Uygulamadan memnuniyet ${t.emotional.satisfaction}/10 / Tekrar yaparım: ${t.emotional.takeAgain?'Evet':'Hayır'}`)+row('Emotions',t.emotional.emotions.map(tr).join(', ')))}${panel('REFLECTION',[['entry','Why I entered'],['confirmation','What confirmed the trade'],['invalidation','What invalidated the setup'],['correct','What I did correctly'],['incorrect','What I did incorrectly'],['differently','What I would do differently']].map(([key,label])=>read(label,t.notes[key])).join(''))}</div></form>`;
}
